{"errorMessage":"Lambda process returned error status code: 1. Result: . Output:\nException in thread \"main\" java.lang.ClassNotFoundException: handlerRequest\n\tat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)\n\tat java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)\n\tat java.base/java.lang.ClassLoader.loadClass(Unknown Source)\n\tat java.base/java.lang.Class.forName0(Native Method)\n\tat java.base/java.lang.Class.forName(Unknown Source)\n\tat cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:209)\n\tat cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:77)","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1423, in do_execute\n    execute_result = lambda_function_callable(inv_context.event, context)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 579, in execute\n    result = lambda_executors.EXECUTOR_LOCAL.execute_java_lambda(\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1532, in execute_java_lambda\n    invocation_result = self._execute_in_custom_runtime(cmd, lambda_function=lambda_function)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1366, in _execute_in_custom_runtime\n    raise InvocationException(\n"]}
